[package]
name = "sig_trace"
version = "0.1.0"
authors = ["cody <codylaeder@gmail.com>"]

[dependencies]
libc ="0.2.15"
regex = "0.1.73"
lazy_static = "0.2.1"
kernelx64 = { git = "https://github.com/valarauca/ExtOpenOptions" }
